stages:
  - test
  - report
  - deploy

ui-tests:
  stage: test
  image: docker:24
  services:
    - docker:24-dind

  before_script:
    - apk add --no-cache docker-compose git

  variables:
    LOGIN: $LOGIN
    PASSWORD: $PASSWORD

  script:
    - docker-compose up --exit-code-from regression || true

  artifacts:
    when: always
    paths:
      - allure-results/
    expire_in: 1 week


allure-report:
  stage: report
  image: docker:24
  services:
    - docker:24-dind

  before_script:
    - apk add --no-cache docker-compose git

  dependencies:
    - ui-tests

  script:
    # history folder
    - mkdir -p allure-results/history

    # generate report exactly like GitHub Actions
    - docker-compose run regression /bin/sh -c "allure generate allure-results --clean -o public"

    # debug
    - ls -la
    - ls -la public

  artifacts:
    paths:
      - public
    expire_in: 1 week


pages:
  stage: deploy

  dependencies:
    - allure-report

  script:
    - echo "Deploy GitLab Pages"
    - ls -la public

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == "main"