stages:
  - test
  - report
  - deploy

ui-tests:
  stage: test
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose up --exit-code-from regression || true
  artifacts:
    paths:
      - allure-results/
    when: always

allure-report:
  stage: report
  image: eclipse-temurin:17-jdk
  dependencies:
    - ui-tests
  before_script:
    - apt-get update
    - apt-get install -y wget unzip
    - wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.zip
    - unzip allure-2.34.1.zip
    - mv allure-2.34.1 /opt/allure
    - ln -s /opt/allure/bin/allure /usr/bin/allure
  script:
    - allure generate allure-results --clean -o public
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  dependencies:
    - allure-report
  script:
    - echo "Deploy Pages"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"