name: UI Tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run UI-tests via docker-compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker compose up --build --exit-code-from regression || true

      - name: Generate Allure report
        run: |
          mkdir -p allure-report
          mkdir -p allure-report
          chmod -R 777 allure-report
          chmod -R 777 allure-results
          
          docker run --rm -v ${{ github.workspace }}:/app -w /app frankescobar/allure-docker-service allure generate allure-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true